name: 💡 Feature request
description: Suggest an idea for Shadowtype
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem or use case?
      description: What are you trying to do that Shadowtype doesn't do well yet?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Anything you've tried or considered?
